In [2]:
import pandas as pd
import numpy as np
from datetime import datetime as dt
from Google import Create_Service
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from pprint import pprint
from datetime import datetime as dt
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import pypyodbc as adbc
import time

Initially, it was important to start by creating a google service account. I'm going to use this account in order to connect to google's API and be allowed to access my spreadsheet created on google sheets. The json file contains all my credentials, including the token, user ID, and private keys which are necessary to establish this connection. Obviously I won't be posting this on Github...

In [3]:
scope = ["https://spreadsheets.google.com/feeds",'https://www.googleapis.com/auth/spreadsheets',"https://www.googleapis.com/auth/drive.file","https://www.googleapis.com/auth/drive"]

In [8]:
creds = ServiceAccountCredentials.from_json_keyfile_name('D:/Python/agile-sprite-311202-a754ede4b3bf.json',scope)
client = gspread.authorize(creds)

During the next 3 steps, I'll be using selenium in order to extract data from the WorldOMeters website. This data will, then, be displayed on a pandas dataframe，whose data will be sent to google sheets in the future.

The first piece of data corresponds, respectively, to the amount of births, deaths, money spent on weight loss programs, money spent on obesity diseases, number of obesity cases, number of people overweight, tons of CO2 emissions (Yearly), Loss of Forests in hectares (Yearly), Non-renewable and Renewable energy spent (Daily), Abortions (Yearly), HIV infected people (Yearly), HIV deaths (Yearly), Cancer Deaths (Yearly), Suicide cases (Yearly), Total of water used (Yearly), People without access to a safe drinking water resource (Yearly), cars produced (Yearly), Public healthcare spenditure (Daily), and money spent on videogames (Daily), all worldwide. I tried to get these statistics by country but couldn't find it anywhere :\

In [1]:
Neu = webdriver.Chrome('D:/Python/chromedriver2.exe')
Neu.get('https://www.worldometers.info/')

Geburten = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/div[3]/div[1]/span[1]/span').text
Tode = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/div[5]/span[1]/span').text
Geld_Gewicht = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/div[39]/div[1]/span[1]/span').text
Geld_Adipositas = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/div[38]/div[1]/span[1]/span').text
Adipositas = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/div[36]/div[1]/span[1]/span').text
Übergewicht = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/div[35]/div[1]/span[1]/span').text
CO2 = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/div[30]/div[1]/span[1]/span').text
Wald_Verlust = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/div[28]/div[1]/span[1]/span').text 
Energie_NichtErneuerbar = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/div[46]/div[1]/span[1]/span').text
Energie_Erneuerbar = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/div[47]/div[1]/span[1]/span').text
Abtreibung = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/div[60]/div[1]/span[1]/span').text
HIV_Infiziert = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/div[62]/div[1]/span[1]/span').text
HIV_Tode = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/div[63]/div[1]/span[1]/span').text
Krebs = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/div[64]/div[1]/span[1]/span').text
Selbstmord = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/div[69]/div[1]/span[1]/span').text
Wasser_Genutzt = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/div[41]/div[1]/span[1]/span').text
LeuteOhneWasser = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/div[43]/div[1]/span[1]/span').text
Herstellung_Autos = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/div[13]/div[1]/span[1]/span').text
Gesundheit_Geld = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/div[10]/div[1]/span[1]/span').text
VideoSpielen_Geld = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/div[21]/div[1]/span[1]/span').text

Spalten = ['Geburten','Tode','Geld_Gewicht','Geld_Adipositas','Adipositas','Übergewicht','CO2','Wald_Verlust','Energie_NichtErneuerbar','Energie_Erneuerbar','Abtreibung','HIV_Infiziert','HIV_Tode','Krebs','Selbstmord','Wasser_Genutzt','LeuteOhneWasser','Herstellung_Autos','Gesundheit_Geld','VideoSpielen_Geld']
Zahlen = [Geburten,Tode,Geld_Gewicht,Geld_Adipositas,Adipositas,Übergewicht,CO2,Wald_Verlust,Energie_NichtErneuerbar,Energie_Erneuerbar,Abtreibung,HIV_Infiziert,HIV_Tode,Krebs,Selbstmord,Wasser_Genutzt,LeuteOhneWasser,Herstellung_Autos,Gesundheit_Geld,VideoSpielen_Geld]

Year = dt.now().strftime('%Y')
Month = dt.now().strftime('%m')
Day = dt.now().strftime('%d')
Hour = dt.now().strftime('%H')
Minute = dt.now().strftime('%M')
Second = dt.now().strftime('%S')
Spalten = ['Jahr','Monat','Tag','Stunde','Minute','Sekunde','Geburten','Tode','Geld_Gewicht','Geld_Adipositas','Adipositas','Übergewicht','CO2','Wald_Verlust','Energie_NichtErneuerbar','Energie_Erneuerbar','Abtreibung','HIV_Infiziert','HIV_Tode','Krebs','Selbstmord','Wasser_Genutzt','LeuteOhneWasser','Herstellung_Autos','Gesundheit_Geld','VideoSpielen_Geld']
Zahlen = [Year, Month, Day, Hour, Minute, Second, Geburten,Tode,Geld_Gewicht,Geld_Adipositas,Adipositas,Übergewicht,CO2,Wald_Verlust,Energie_NichtErneuerbar,Energie_Erneuerbar,Abtreibung,HIV_Infiziert,HIV_Tode,Krebs,Selbstmord,Wasser_Genutzt,LeuteOhneWasser,Herstellung_Autos,Gesundheit_Geld,VideoSpielen_Geld]

WeltStat = pd.DataFrame([Zahlen],columns=Spalten)

NameError: name 'webdriver' is not defined

The next piece of data corresponds to data involving the 8 continents of the world (If you consider north, central, and south america as continents), and how large is the population for each of those. The variable names are in German but then again if you know English I don't think it'll be hard to guess which continent is which just looking at them.

In [20]:
Neu = webdriver.Chrome('D:/Python/chromedriver2.exe')
Neu.get('https://www.worldometers.info/world-population/asia-population/')
Asien_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div/div[1]/div/span').text
Neu.get('https://www.worldometers.info/world-population/europe-population/')
Europa_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div/div[1]/div/span').text
Neu.get('https://www.worldometers.info/world-population/oceania-population/')
Oceanien_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div/div[1]/div/span').text
Neu.get('https://www.worldometers.info/world-population/south-america-population/')
Sudamerika_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div/div[1]/div/span').text
Neu.get('https://www.worldometers.info/world-population/northern-america-population/')
Nordamerika_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div/div[1]/div/span').text
Neu.get('https://www.worldometers.info/world-population/central-america-population/')
Centralamerika_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div/div[1]/div/span').text
Neu.get('https://www.worldometers.info/world-population/africa-population/')
Afrika_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div/div[1]/div/span').text
Year = dt.now().strftime('%Y')
Month = dt.now().strftime('%m')
Day = dt.now().strftime('%d')
Hour = dt.now().strftime('%H')
Minute = dt.now().strftime('%M')
Second = dt.now().strftime('%S')

dic = {'Jahr':[Year]*7,'Monat':[Month]*7,'Tag':[Day]*7,'Uhr':[Hour]*7,'Minute':[Minute]*7,'Sekunde':[Second]*7,'Kontinent':['Asien','Afrika','Sudamerika','Nordamerika','Centralamerika','Oceanien','Europa'],'Bevölkerung':[Asien_Völker,Afrika_Völker,Sudamerika_Völker,Nordamerika_Völker,Centralamerika_Völker,Oceanien_Völker,Europa_Völker]}
Völker_Kontinenten = pd.DataFrame(data = dic)

The next piece of data corresponds to data involving the 20 most populated countries in the world, and how large is the population for each of those. The variable names are written German but then again if you know English I don't think it'll be hard to guess which continent is which simply by looking at them. The only ones I think you'll have trouble with is Russland = Russia, Äthiopien = Ethiopia, Ägypten = Egypt, Deutschland = Germany, and Türkei = Turkey.

In [21]:
Neu = webdriver.Chrome('D:/Python/chromedriver2.exe')
Neu.get('https://www.worldometers.info/world-population/')
China_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[3]/div[1]/div/div[2]/div[1]/div[1]/span[4]/span').text
Indien_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[3]/div[1]/div/div[2]/div[1]/div[2]/span[4]/span').text
USA_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[3]/div[1]/div/div[2]/div[1]/div[3]/span[4]/span').text
Indonesien_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[3]/div[1]/div/div[2]/div[1]/div[4]/span[4]/span').text
Pakistan_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[3]/div[1]/div/div[2]/div[1]/div[5]/span[4]/span').text
Brasilien_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[3]/div[1]/div/div[2]/div[1]/div[6]/span[4]/span').text
Nigeria_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[3]/div[1]/div/div[2]/div[1]/div[7]/span[4]/span').text
Bangladesch_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[3]/div[1]/div/div[2]/div[1]/div[8]/span[4]/span').text
Russland_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[3]/div[1]/div/div[2]/div[1]/div[9]/span[4]/span').text
Mexiko_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[3]/div[1]/div/div[2]/div[1]/div[10]/span[4]/span').text
Japan_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[3]/div[1]/div/div[2]/div[2]/div[1]/span[4]/span').text
Äthiopien_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[3]/div[1]/div/div[2]/div[2]/div[2]/span[4]/span').text
Philippinen_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[3]/div[1]/div/div[2]/div[2]/div[3]/span[4]/span').text
Ägypten_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[3]/div[1]/div/div[2]/div[2]/div[4]/span[4]/span').text
Vietnam_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[3]/div[1]/div/div[2]/div[2]/div[5]/span[4]/span').text
Kongo_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[3]/div[1]/div/div[2]/div[2]/div[6]/span[4]/span').text
Türkei_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[3]/div[1]/div/div[2]/div[2]/div[7]/span[4]/span').text
Iran_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[3]/div[1]/div/div[2]/div[2]/div[8]/span[4]/span').text
Deutschland_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[3]/div[1]/div/div[2]/div[2]/div[9]/span[4]/span').text
Thailand_Völker = Neu.find_element_by_xpath('/html/body/div[3]/div[3]/div[1]/div/div[2]/div[2]/div[10]/span[4]/span').text

Länder = ['China','Indien','USA','Indonesien','Pakistan','Brasilien','Nigeria','Bangladesch','Russland','Mexiko','Japan','Äthiopien','Philippinen','Ägypten','Vietnam','Kongo','Türkei','Iran','Deutschland','Thailand']
Daten_Länder = [China_Völker,Indien_Völker,USA_Völker,Indonesien_Völker,Pakistan_Völker,Brasilien_Völker,Nigeria_Völker,Bangladesch_Völker,Russland_Völker,Mexiko_Völker,Japan_Völker,Äthiopien_Völker,Philippinen_Völker,Ägypten_Völker,Vietnam_Völker,Kongo_Völker,Türkei_Völker,Iran_Völker,Deutschland_Völker,Thailand_Völker]
Year = dt.now().strftime('%Y')
Month = dt.now().strftime('%m')
Day = dt.now().strftime('%d')
Hour = dt.now().strftime('%H')
Minute = dt.now().strftime('%M')
Second = dt.now().strftime('%S')
dic = {'Jahr':[Year]*20,'Monat':[Month]*20,'Tag':[Day]*20,'Uhr':[Hour]*20,'Minute':[Minute]*20,'Sekunde':[Second]*20,'Land':Länder,'Bevölkerung':Daten_Länder}
Völker_Top20Länder = pd.DataFrame(data = dic)

Next step will be to create 3 different variables, which can be used either to store data, or to retrieve data from the google sheets website.

In [5]:
Welt_Blatt = client.open('上古卷轴').worksheet('世界数据')
Länder_Blatt = client.open('上古卷轴').worksheet('Länder-Top20')
Kontinenten_Blatt = client.open('上古卷轴').worksheet('Kontinenten-Völker')

I've decided to perform this process later on in order to make sure that all the data that I would get would be from approximately the same time. It may differ from 1 to 3 minutes time depending on the amount of pages that had to be visited during this period, however it is still useful data to be able to compare.

First data to be stored will be the data included on the main page of the website. This data correspond to statistics from the whole world constantly being displayed there. It will be necessary, in order to do so, to run through the pandas dataframe created using a loop and store its values on each google sheet's cell at a time. It's also important to set 120 seconds of time sleep in between this transfer and the next one due to the maximum amount of requests per minute allowed by google.

In [23]:
Linien_Überspringen = pd.DataFrame(data = Welt_Blatt.get_all_records()).shape[0] + 1
for i in range(len(WeltStat.iloc[0].tolist())):
    Welt_Blatt.update_cell(Linien_Überspringen+1,i+1,int(WeltStat.iloc[0].tolist()[i].replace(",","")))
time.sleep(120)
pd.DataFrame(data = Welt_Blatt.get_all_records())

,Jahr,Monat,Tag,Stunde,Minute,Sekunde,Geburten,Tode,Geld_Gewicht,Geld_Adipositas,...,Abtreibung,HIV_Infiziert,HIV_Tode,Krebs,Selbstmord,Wasser_Genutzt,LeuteOhneWasser,Herstellung_Autos,Gesundheit_Geld,VideoSpielen_Geld
0,2022,2,13,12,2,4,16695723,7009264,94958508,308584904,...,5087783,43403115,200.329,978.719,127.790,533509686,784591908,9794521,7969264049,153451891
1,2022,2,13,18,1,19,16.791.488,7.049.469,142.214.461,462.162.991,...,5.116.974,43.403.742,201.478,984.333,128.523,536.575.462,784.585.520,9.850.870,11.935.063.267,229.814.796
2,2022,2,14,0,2,39,16.887.792,7.089.900,348.122,1.131.342,...,5.146.330,43.404.382,202.633,989.978,129.260,539.658.760,784.579.095,9.907.543,29.289.906,563.989
3,2022,2,14,6,1,47,16.983.511,7.130.085,47.581.645,154.636.600,...,5.175.508,43.405.009,203.782,995.589,129.992,542.723.377,784.572.709,9.963.873,3.993.418.055,76.894.734
4,2022,2,14,11,9,14,17065453,7164486,88016542,286052949,...,5200485,43405546,204765.000,1000393.000,130620.000,545346936,784567243,10012097,7387098669,142241326

Second data to be stored will be data included corresponding to the top 20 most populated countries in the world. Besides running through the pandas dataframe, it will also be necessary to determine a period for the program to stop for 120 seconds every 3 loops  due to the maximum amount of requests per minute that is allowed by google. After the last loop, there still is another 120 seconds to wait to transfer the last piece of data for the same reason.

In [194]:
Linien_Überspringen = pd.DataFrame(data = Länder_Blatt.get_all_records()).shape[0] + 1
for i in range(len(Völker_Top20Länder.iloc[0].tolist())):
    if (i+1) % 3 == 0:
        time.sleep(120)
    for j in range(20):
        Länder_Blatt.update_cell(Linien_Überspringen+1+j,i+1,Völker_Top20Länder.iloc[j].tolist()[i].replace(",",""))
    
pd.DataFrame(data = Länder_Blatt.get_all_records())
time.sleep(120)

1
2
3
4
5
6
7
8

Data corresponding to each continent's population. 120 seconds after the last import to google sheets the last piece of data will bee transfered :)

In [195]:
Linien_Überspringen = pd.DataFrame(data = Kontinenten_Blatt.get_all_records()).shape[0] + 1
for i in range(len(Völker_Kontinenten.iloc[0].tolist())):
    for j in range(7):
        Kontinenten_Blatt.update_cell(Linien_Überspringen+1+j,i+1,Völker_Kontinenten.iloc[j].tolist()[i].replace(",",""))
    
pd.DataFrame(data = Kontinenten_Blatt.get_all_records())

    Jahr  Monat  Tag  Uhr  Minute  Sekunde       Kontinent  Bevölkerung
0   2022      2   12   15      41       42           Asien   4706163252
1   2022      2   12   15      41       42          Afrika   1395108509
2   2022      2   12   15      41       42      Sudamerika    436598949
3   2022      2   12   15      41       42     Nordamerika    372580063
4   2022      2   12   15      41       42  Centralamerika    183102705
5   2022      2   12   15      41       42        Oceanien     43585028
6   2022      2   12   15      41       42          Europa    748371961
7   2022      2   13    8      21       30           Asien   4706240065
8   2022      2   13    8      21       30          Afrika   1395173665
9   2022      2   13    8      21       30      Sudamerika    436605837
10  2022      2   13    8      21       30     Nordamerika    372584433
11  2022      2   13    8      21       30  Centralamerika    183106766
12  2022      2   13    8      21       30        Oceanien     43586102
13  2022      2   13    8      21       30          Europa    748372823

The next steps to transfer the data from Google Sheets to SQL and from SQL to Power BI will be available on the other document I'll be posting on GitHub ;)